# Site settings
title: Arc Reactor
email: dan@nocturnalcode.com
description: > # this means to ignore newlines until "baseurl:"
  Some thoughts and reference material.
  Objective-C | Swift | Ruby
baseurl: "" # the subpath of your site, e.g. /blog/
url: "danbrooker.github.io" #"http://arc-reactor.com" # the base hostname & protocol for your site
twitter_username: draconisNZ
github_username:  danbrooker

# Build settings
markdown: kramdown
